### ISSUE TITLE
nodal : new poly command not working

### ISSUE THREAD

**Issue by theethiopian** [poly/dotcom#1]
Not sure if this is the right place to do this but this command is not working from the CLI. Not sure if anyone else is having this issue. 
poly:new [projectName]

**Comment by keithwhor** [comment]
You can only use the poly commands from Nodal right now.

```nodal poly:new [projectName]```.

It must be a valid Nodal project. That help?

**Comment by theethiopian** [comment]
That wasn't quite it. But that helped me figure out the core issue. It was with how I was using poly. Thank you @keithwhor for being so responsive and creating such an easy to use and pretty well documented project.

**Comment by theethiopian** [comment]
On Tue, Jul 12, 2016 at 8:50 PM, Keith Horwood <notifications@github.com>
wrote:

> nodal poly:new [projectName


Sorry to bother you now I'm getting

Creating project "TGA"...

*Error: *Validation error after running the command from Nodal

Eyasu Felleke
efelleke@gmail.com
(559)362-9034

**Comment by theethiopian** [comment]
@keithwhor

**Comment by keithwhor** [comment]
Upgrade your global nodal version to 0.12.5 and try again :). Just pushed changes. It should display which errors you're getting.

Cheers,
- Keith

**Comment by theethiopian** [comment]
Of course. Dependencies thanks for your help. Have a great night. 

Eyasu Felleke || eyasu@eyasufelleke.com ||
559-362-9034 || joshuasroasting.com ||
